language: node_js
node_js:
- iojs
env:
  global:
  - secure: WXkeUKwWKTv2uUCyIiDdQ0e5gQCoX9gGj6wiNh9G7IATqcecxTw6cpQGj3J8YWDIjbtNXfAkJwohhGtXYr7VnkXRA1s0POYM+8cvM5I+ZDtZkXM9EvCwMYxf9XZ8qQ/4fegeSoZqfx1qgh+Sfh6Wp93I4W+AfB8VONLIGgXr172QGwYmkynPpC//mYA6sUZoQo4Y796PtBblc+7oM0a5A5chQ5r1CVqPqRZ/i9aNrH2UTdYjCMNE395LqwHSJGk5eunT5ebA4OcClme1wL78MJtGS1ZZIOEHSBv7mBrOcp29kYknc/m1PaOYBMdppmRBLr6Q5oUg8QzaILW2TypsWkosWpSlbemW1lsutqlFRkmtsjfX3ZVOoeIx/7J9v+pDA2gb7VMtNzwlkRpcLfHBmfuXuiPNXwLS1Ogl2D8JUD+rjwB3FI6pE2zZqNL7zMe7yhCQ/1wqGdlNqB1Ifb9T2RRkDCEUr+dw3sGn6Ecgk4XThUwY3vVzABj0C906Wc7UpsVvf1qjLCRg48lYG8kmhLqEylL+IUs3XXMSv69/YLxnDvRdF/d1FZHWKcoTeWYmXr3k1q0ePYEDXpX6/8MXWix1Qql4AAOjIxOgRufBPlDWe6QS2b97K4OPo+m3cf/RaLPz+jUOpf59l6CNnceBYLKs00Taf0KSgs+YVADAV6M=
before_script:
- git config --global user.email "basaratali@gmail.com"
- git config --global user.name "Travis-CI"
- git remote set-url origin https://github.com/TypeStrong/ntypescript.git
script:
- bash prepare.sh
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git config --global push.default matching
- bash release.sh
branches:
  only:
  - master
deploy:
  provider: npm
  email: basaratali@gmail.com
  api_key:
    secure: I37/GqFRAVr2AGU+iNomEPSyxvM8RwQM8hnVzJ2ICsu8FEE+QVN12XZzbfemDSuvYOdhr6xAI9naJOIMz/W/monRwjNE57SY3xibpm/GJ/68yXJm9naHKNGhwZoCfPHA/kdsc7X9L3v6xNmnc5B+0+NDKEhqIZzYwsxurAmsdPE/IFfcxP6T7WTGuRPncNbD8UZU61avVIyWfkY5XzujVIjh/zKqYese0dPUzngy22zk/iIx5GRIkoAXmMPrvl8dfj9jqJC+FHBb/nBvhOJsLEk6vsYig44q2VUMR54wmg9y6GB0/7Sia6032i4LPrBV4k4HUQQDrk/NEelk6qG+3Mbkzz7TmEkImHKwgUPSjsQq/BtVXNz1WAeB7OBuOldOaGm74tb4hjR20G7vp24Gx6KGNnVgUM71xKMxsjWxEJaAExuLCTFgm84UjGwPJemmW8f4YCMsuvIGGh+aXpyZz3fxWUSBmJCJFJtBHi8RH/PfEbxVjHofyCq3oacPK05pulDF3ThjQcs892hZBodNZOuScVHKsQUpN+rzGyPTyaD9GNdVGlSQw79ui07bRl/Neolh7YHPn/sfYxHn/WP+v/jN0KC2y7LgeIqAY1KJQ1Ut229OfqaNFRVfw9c0txrPjj2MQOsWRJkPdimMxS6m/74A4lv2ITQaui2t9PMyI4s=
  on:
    tags: true
    repo: TypeStrong/ntypescript
